# Async Minion config for CAA Data Dammages
quarkus.http.port=8081
quarkus.log.level=INFO
quarkus.log.console.level=INFO

# Connect to Microcks main app
io.github.microcks.minion.async.client.MicrocksAPIConnector/mp-rest/url=http://microcks:8080
microcks.serviceaccount.name=microcks-serviceaccount
microcks.serviceaccount.credentials=f3674e4a-5696-437f-b201-598d06b32b01

# Kafka connection - Microcks property
kafka.bootstrap-server=kafka:29092

# Kafka connection - Quarkus SmallRye Reactive Messaging
%prod.kafka.bootstrap.servers=kafka:29092
mp.messaging.connector.smallrye-kafka.bootstrap.servers=kafka:29092

# Disable Kafka health (avoids blocking startup on localhost check)
quarkus.kafka.health.enabled=false

# Async features
async-api.default-binding=KAFKA
async-api.default-frequency=5
